coverage_service: coveralls
xcodeproj: HyperwalletUISDK.xcodeproj
scheme: HyperwalletTransferMethod
ignore:
  - Tests/*
  - UITests/*
  - Demo/*
  - HyperwalletCommon/*
  - HyperwalletTransferMethod/Extensions/*
  - HyperwalletTransferMethod/Helper/*
  - HyperwalletTransferMethod/View/*
  - HyperwalletTransferMethod/*Controller.swift
  - HyperwalletTransferMethod/*Cell.swift
  - HyperwalletTransferMethod/AddTransferMethodSectionData.swift
  - HyperwalletTransferMethod/TransferMethodTypeDetail.swift
