coverage_service: coveralls
xcodeproj: HyperwalletUISDK.xcodeproj
scheme: HyperwalletUISDK
ignore:
  - UITests/*
  - Demo/*
  - "*/Sources/Resources/*"
  - "*/Sources/Extensions/*"
  - "*/Sources/Localization/*"
  - "*/Sources/Helper/*"
  - "*/Sources/View/*"
  - "*/Sources/*/*Controller.swift"
  - "*/Sources/*/*Cell.swift"
  - "*/Sources/TransferMethod/AddTransferMethodSectionData.swift"
  - "*/Sources/HyperwalletUI.swift"
  - "*/Tests/*"
