coverage_service: coveralls
xcodeproj: HyperwalletUISDK.xcodeproj
scheme: HyperwalletUISDK
ignore:
  - Tests/*
  - UITests/*
  - Demo/*
  - Sources/Resources/*
  - Sources/Extensions/*
  - Sources/Generics/*
  - Sources/Localization/*
  - Sources/Helper/*
  - Sources/View/*
  - Sources/*/*Controller.swift
  - Sources/*/*Cell.swift
  - Sources/TransferMethod/AddTransferMethodSectionData.swift
  - Sources/HyperwalletUI.swift
  - "*/Sources/Extensions/*"
  - "*/Tests/*"
  - "*/Sources/Helper/*"
