coverage_service: coveralls
xcodeproj: HyperwalletUISDK.xcodeproj
scheme: HyperwalletUISDK
#build_directory: /Users/travis/Library/Developer/Xcode/DerivedData/HyperwalletUISDK-cfsslzuyjqnvsygegrzknunznqya/Build/Products
source_directory: HyperwalletUISDK
#binary_file: /Users/travis/Library/Developer/Xcode/DerivedData/HyperwalletUISDK-cfsslzuyjqnvsygegrzknunznqya/Build/Products/Release-iphonesimulator/HyperwalletUISDK.framework/HyperwalletUISDK
configuration: Debug
ignore:
  - Tests/*
  - UITests/*
  - Demo/*
  - Sources/Resources/*
  - Sources/Extensions/*
  - Sources/Generics/*
  - Sources/Localization/*
  - Sources/Helper/*
  - Sources/View/*
  - Sources/TransferMethod/*Controller.swift
  - Sources/TransferMethod/*Cell.swift
  - Sources/TransferMethod/AddTransferMethodSectionData.swift
  - Sources/HyperwalletUI.swift
