language: swift
osx_image: xcode10.1
os: osx
branches:
 only:
  - /.*/
# cache:
#    directories:
#      - Carthage
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - PROJECT=HyperwalletUISDK.xcodeproj
  - IOS_FRAMEWORK_SCHEME="TransferMethod"
  - IOS_UI_TESTS_SCHEME="Demo"

  matrix:
    - ios_version='12.1'  ios_device='iPhone XR' scheme="$IOS_FRAMEWORK_SCHEME" platform='iOS Simulator' configuration="Debug" code_coverage="YES" only_active_arch="YES"
    - ios_version='12.1'  ios_device='iPhone XR' scheme="$IOS_UI_TESTS_SCHEME"  platform='iOS Simulator' configuration="XCUITest" code_coverage="NO" only_active_arch="NO"
    - ios_version='11.1'  ios_device='iPhone 7'  scheme="$IOS_UI_TESTS_SCHEME"  platform='iOS Simulator' configuration="XCUITest" code_coverage="NO" only_active_arch="NO"

before_install:
  # Boot the emulator by ID
  - |
     ios_uid=$(xcrun instruments -s devices | grep Simulator | grep "$ios_device ($ios_version)*" | grep -o "[0-9A-F]\{8\}-[0-9A-F]\{4\}-[0-9A-F]\{4\}-[0-9A-F]\{4\}-[0-9A-F]\{12\}")
     xcrun simctl boot $ios_uid
  # List all emulator available
  - xcrun simctl list
  # Update the brew and build dependencies tools
  - brew outdated carthage || brew upgrade carthage
  - Carthage update --platform iOS  --cache-builds
  - gem i slather --no-ri --no-rdoc
  # Force to update the Swiftlint to the last stable version
  - brew outdated swiftlint || brew upgrade swiftlint
  # Print the booted emulator
  - xcrun simctl list | grep "(Booted)"
  # Print the swiftlint version
  - swiftlint version
script: |
  set -o pipefail
  set -e

  # Define the destination emulator
  destination="platform=$platform,OS=$ios_version,name=$ios_device"

  # Build and test Framework in Debug
  xcodebuild -enableCodeCoverage "$code_coverage" clean build test -project "$PROJECT" \
    -scheme "$scheme" \
    -destination "$destination" \
    -configuration "$configuration" ONLY_ACTIVE_ARCH="$only_active_arch" ENABLE_TESTABILITY=YES CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO

  # Lint - Add `--strict` to fail for warning and violation
  swiftlint lint --reporter json
after_success:
 if [ "$code_coverage" == "YES" ]; then
      slather;
 fi
notifications:
  slack:
    secure: oqibkB7miMOa4w1HKWpLFwgBRf1LM9hlOy2c5QcID291rfJ33h24U1twGVRk860pFslTa0FFT4Hb9uzSbVtCG4mrvtpw673VhzxNwLJW0jx0co86vRM1ULoU5Xs3vxNrLiXXcnb9Sz6rcJeCzyWfnU0FnEhWxGFNyKNBB5UJHgnzpmJYQncv3DVfjpGMfPaO8N9dq2m2UPqd6tedt0DwEMJ28Zg1pqv1uU4hClf9e9AKIjFLDgFhyAIw2nZ4h56jFeXSk+Z9/j3Vv+621uDegt3yNWNFa+WLZh62HdnnukMcVJzVFFtgS0/j53rtTJ1Ayg5GroqaL28khakVt81AsKgUp+HQHHBn43ee3JCj72uTu+SEWbCit4NYYZLzByOa4IunGTKBCWPGaomizSfNKTBFadvIi4XzABA6Dg5agZDd8P6toH9JSIgAPCGku+3iHvCqVJnK1fkTShjrkKNpKr5ry5SP1EH72OC1vTxOMahlRsygIwDiUOFMz78lEtHV0a/2onwkeIPI0segYBDdP6pbEBQUrCmTNw2guhDyopIKaEzhwWphcky9v5lT1oqsjdNPAESW+/5uWETXLMeNI7bc3fWy8xVECJUyeX0ZDwJU2zFOyoD+Mxn1pnhMcWhX3yFMPAhVEEAC02YVKTsjOJQgbmv9K7Stv3HbSUenR3Y=
