language: objective-c
osx_image: xcode9.3beta
before_script:
  - brew update && brew upgrade swiftlint
script:
  - bundle exec fastlane scan --code_coverage true
  - bundle exec danger
after_success:
  - bash <(curl -s https://codecov.io/bash) -J 'Hippolyte'